import type { RequestWords } from './types'

export const de: RequestWords = {
  spaced: true,
  numbers: {
    ein: 1,
    eine: 1,
    einer: 1,
    einen: 1,
    zwei: 2,
    drei: 3,
    vier: 4,
    fünf: 5,
    sechs: 6,
    sieben: 7,
    acht: 8,
    neun: 9,
    zehn: 10,
    elf: 11,
    zwölf: 12,
    fünfzehn: 15,
    zwanzig: 20,
    dreißig: 30,
    vierzig: 40,
    fünfundvierzig: 45,
    fünfzig: 50,
    sechzig: 60,
    neunzig: 90,
  },
  interval: {
    before: ['alle', 'jede', 'jeden', 'jedes'],
    after: [],
    units: {
      second: ['sekunde', 'sekunden', 'sek'],
      minute: ['minute', 'minuten', 'min'],
      hour: ['stunde', 'stunden', 'std'],
      day: ['tag', 'tage', 'tagen'],
    },
    hourly: ['stündlich'],
    halfHour: ['(alle|jede) halbe stunde', 'halbstündlich'],
  },
  daily: {
    day: ['jeden tag', 'täglich', 'tagtäglich'],
    morning: ['jeden morgen', 'jeden vormittag', 'morgens', 'jeden früh'],
    afternoon: ['jeden nachmittag', 'nachmittags'],
    evening: ['jeden abend', 'abends'],
    night: ['jede nacht', 'nachts'],
  },
  dayparts: {
    morning: ['morgen', 'morgens', 'vormittag', 'vormittags', 'früh'],
    afternoon: ['nachmittag', 'nachmittags'],
    evening: ['abend', 'abends'],
    night: ['nacht', 'nachts'],
  },
  weekly: {
    before: ['jeden', 'jede', 'immer', 'am', 'an jedem', 'immer am'],
    after: [],
    days: [
      ['sonntag'],
      ['montag'],
      ['dienstag'],
      ['mittwoch'],
      ['donnerstag'],
      ['freitag'],
      ['samstag', 'sonnabend'],
    ],
    alone: [['sonntags'], ['montags'], ['dienstags'], ['mittwochs'], ['donnerstags'], ['freitags'], ['samstags', 'sonnabends']],
  },
  once: {
    once: ['einmal', 'einmalig'],
    today: ['heute'],
    tomorrow: ['morgen', 'übermorgen'],
    notTomorrow: ['heute morgen', 'jeden morgen', 'am morgen', 'guten morgen'],
  },
  clock: {
    at: ['um', 'gegen', 'ab'],
    hour: ['uhr', 'h'],
    minute: [],
    half: [],
    am: [],
    pm: [],
    meridiemFirst: false,
  },
  notify: {
    none: [
      'nicht benachrichtigen',
      'benachrichtige mich nicht',
      'keine benachrichtigung',
      'ohne benachrichtigung',
      'nur speichern',
    ],
    change: [
      '(wenn|falls|sobald) sich (etwas|es|das|das ergebnis|der inhalt|die seite) ändert',
      '(nur )?bei (einer )?änderung',
      '(nur )?bei änderungen',
    ],
    significant: ['(nur wenn|nur falls|wenn|falls)…(wichtig|bedeutend|relevant)', 'eine benachrichtigung wert'],
    available: [
      'wieder (auf lager|verfügbar|lieferbar|vorrätig)',
      'auf lager',
      'vorrätig',
      '(verfügbar|lieferbar) (ist|wird)',
      'nicht (mehr )?(auf lager|verfügbar|lieferbar)',
      'ausverkauft',
    ],
    below: ['unter', 'unterhalb von', 'weniger als', 'günstiger als', 'billiger als', 'niedriger als'],
    above: ['über', 'oberhalb von', 'mehr als', 'teurer als', 'höher als'],
    belowAfter: [],
    aboveAfter: [],
  },
  currencies: { franken: 'CHF' },
  multipliers: {},
  currency: 'EUR',
  names: {
    stock: ['lager', 'auf lager', 'vorrätig', 'lagerbestand'],
    release: ['release', 'releases', 'version', 'versionen', 'veröffentlichung', 'veröffentlichungen'],
    research: ['recherche', 'recherchiere', 'recherchieren'],
  },
  task: {
    dropAtEnd: [
      '(,)? und (sag|sage) mir(,)? (ob|wenn|falls) der preis (unter|über) # (liegt|ist|fällt|steigt)',
      '(,)? und benachrichtige mich nur(,)? wenn (er|sie|es) wieder verfügbar ist',
    ],
    price: ['preis', 'preise'],
    reportPrice: 'Nenne den aktuellen Preis',
    fullStop: '. ',
  },
}
