import type { RequestWords } from './types'

export const it: RequestWords = {
  spaced: true,
  numbers: {
    un: 1,
    uno: 1,
    una: 1,
    due: 2,
    tre: 3,
    quattro: 4,
    cinque: 5,
    sei: 6,
    sette: 7,
    otto: 8,
    nove: 9,
    dieci: 10,
    undici: 11,
    dodici: 12,
    quindici: 15,
    venti: 20,
    trenta: 30,
    quaranta: 40,
    quarantacinque: 45,
    cinquanta: 50,
    sessanta: 60,
    novanta: 90,
  },
  interval: {
    before: ['ogni', 'tutte le', 'tutti i'],
    after: [],
    units: {
      second: ['secondo', 'secondi'],
      minute: ['minuto', 'minuti', 'min'],
      hour: ['ora', 'ore'],
      day: ['giorno', 'giorni'],
    },
    hourly: ['ogni ora'],
    halfHour: ["ogni mezz'ora", 'ogni mezzora', 'ogni mezza ora'],
  },
  daily: {
    day: ['ogni giorno', 'tutti i giorni', 'quotidianamente'],
    morning: ['ogni mattina', 'ogni mattino', 'tutte le mattine'],
    afternoon: ['ogni pomeriggio', 'tutti i pomeriggi'],
    evening: ['ogni sera', 'tutte le sere'],
    night: ['ogni notte', 'tutte le notti'],
  },
  dayparts: {
    morning: ['mattina', 'mattine', 'mattino'],
    afternoon: ['pomeriggio', 'pomeriggi'],
    evening: ['sera', 'sere', 'serata'],
    night: ['notte', 'notti'],
  },
  weekly: {
    before: ['ogni', 'tutti i', 'tutte le', 'il', 'la', 'di'],
    after: [],
    days: [
      ['domenica', 'domeniche'],
      ['lunedì', 'lunedi'],
      ['martedì', 'martedi'],
      ['mercoledì', 'mercoledi'],
      ['giovedì', 'giovedi'],
      ['venerdì', 'venerdi'],
      ['sabato', 'sabati'],
    ],
  },
  once: {
    once: ['una volta', 'una sola volta'],
    today: ['oggi', 'stasera', 'stamattina', 'stanotte'],
    tomorrow: ['domani', 'dopodomani'],
  },
  clock: {
    at: ['alle ore', 'alle', "all'", 'verso le', 'ore'],
    hour: ['h'],
    minute: [],
    half: ['e mezza', 'e mezzo'],
    am: [],
    pm: [],
    meridiemFirst: false,
  },
  notify: {
    none: ['non (notificarmi|avvisarmi)', 'nessuna notifica', 'senza (notifica|notifiche)', '(salva|salvare) (solo|soltanto)', 'solo salvare'],
    change: [
      '(quando|se) (cambia|cambiano|qualcosa cambia)',
      '(quando|se) (la pagina|il risultato|il contenuto) cambia',
      'in caso di (modifiche|cambiamenti)',
    ],
    significant: ['(solo se|soltanto se|se|quando)…(importante|significativo|rilevante)', 'merita una notifica'],
    available: [
      'di nuovo (disponibile|in stock|in magazzino)',
      '(è|torna|torni|diventa|sarà) disponibile',
      'in (stock|magazzino)',
      'esaurito',
    ],
    below: ['sotto( i| a| ai| al)?', 'al di sotto di', 'meno di', 'inferiore a', 'scende sotto( i| a| ai)?'],
    above: ['sopra( i| a| ai| al)?', 'al di sopra di', 'più di', 'superiore a', 'supera( i)?'],
    belowAfter: [],
    aboveAfter: [],
  },
  currencies: {},
  multipliers: {},
  currency: 'EUR',
  names: {
    stock: ['magazzino', 'stock', 'scorte', 'esaurito'],
    release: ['versione', 'versioni', 'release', 'rilascio', 'rilasci'],
    research: ['ricerca', 'ricerche'],
  },
  task: {
    dropAtEnd: [
      ' e (dimmi|avvisami|fammi sapere) se il prezzo (scende sotto( i)?|sale sopra( i)?|è sotto( i)?|è sopra( i)?|è inferiore a|è superiore a|supera( i)?) #',
    ],
    price: ['prezzo', 'prezzi'],
    reportPrice: 'Indica il prezzo attuale',
    fullStop: '. ',
  },
}
