import type { RequestWords } from './types'

// Korean puts spaces between words but attaches particles (금요일마다,
// 8시에), so phrases match inside words, as in Japanese and Chinese.
export const ko: RequestWords = {
  spaced: false,
  numbers: {
    한: 1,
    두: 2,
    세: 3,
    네: 4,
    다섯: 5,
    여섯: 6,
    일곱: 7,
    여덟: 8,
    아홉: 9,
    열: 10,
    열두: 12,
  },
  interval: {
    before: ['매'],
    after: ['마다', '에 한 번', '간격으로'],
    units: {
      second: ['초'],
      minute: ['분'],
      hour: ['시간'],
      day: ['일'],
    },
    hourly: ['매시간', '매 시간', '한 시간마다'],
    halfHour: ['30분마다', '반 시간마다'],
  },
  daily: {
    day: ['매일', '날마다', '하루에 한 번'],
    morning: ['매일 아침', '아침마다', '매일 오전'],
    afternoon: ['매일 오후', '오후마다'],
    evening: ['매일 저녁', '저녁마다'],
    night: ['매일 밤', '밤마다'],
  },
  dayparts: {
    morning: ['아침', '오전', '새벽'],
    afternoon: ['오후', '낮'],
    evening: ['저녁'],
    night: ['밤'],
  },
  weekly: {
    before: ['매주', '매'],
    after: ['마다'],
    days: [['일요일'], ['월요일'], ['화요일'], ['수요일'], ['목요일'], ['금요일'], ['토요일']],
    alone: [['일요일'], ['월요일'], ['화요일'], ['수요일'], ['목요일'], ['금요일'], ['토요일']],
  },
  once: {
    once: ['한 번', '한번', '1회', '한 번만'],
    today: ['오늘'],
    tomorrow: ['내일', '모레'],
  },
  clock: {
    at: [],
    hour: ['시'],
    minute: ['분'],
    half: ['반'],
    am: ['오전', '아침', '새벽'],
    pm: ['오후', '저녁', '밤'],
    meridiemFirst: true,
  },
  notify: {
    none: ['알림 없이', '알리지 마', '알림을 보내지 마', '알림 끄', '저장만'],
    change: ['바뀌면', '변경되면', '변하면', '달라지면', '변경이 있으면', '바뀔 때', '변경될 때'],
    significant: ['중요한 (경우|때|것)', '중요하면', '알릴 만한', '알릴만한'],
    available: ['재입고', '입고되면', '구매 가능', '재고가 (생기|있으|들어오)', '품절'],
    below: [],
    above: [],
    belowAfter: ['이하', '미만', '아래', '밑으로', '보다 (싸|저렴|낮)'],
    aboveAfter: ['이상', '초과', '넘으면', '넘을', '보다 (비싸|높)', '위로'],
  },
  currencies: { 원: 'KRW', '₩': 'KRW', 달러: 'USD', 유로: 'EUR', 엔: 'JPY' },
  multipliers: { 천: 1000, 만: 10000, 억: 100000000 },
  currency: 'KRW',
  names: {
    stock: ['재고', '입고', '품절'],
    release: ['릴리스', '출시', '버전', '새 버전'],
    research: ['조사', '리서치'],
  },
  task: {
    dropAtEnd: [],
    price: ['가격', '값'],
    reportPrice: '현재 가격을 알려 주세요',
    fullStop: '. ',
  },
}
