import type { RequestWords } from './types'

export const ptBR: RequestWords = {
  spaced: true,
  numbers: {
    um: 1,
    uma: 1,
    dois: 2,
    duas: 2,
    três: 3,
    tres: 3,
    quatro: 4,
    cinco: 5,
    seis: 6,
    sete: 7,
    oito: 8,
    nove: 9,
    dez: 10,
    onze: 11,
    doze: 12,
    quinze: 15,
    vinte: 20,
    trinta: 30,
    quarenta: 40,
    'quarenta e cinco': 45,
    cinquenta: 50,
    sessenta: 60,
    noventa: 90,
  },
  interval: {
    before: ['a cada', 'cada', 'todos os', 'todas as'],
    after: [],
    units: {
      second: ['segundo', 'segundos'],
      minute: ['minuto', 'minutos', 'min'],
      hour: ['hora', 'horas'],
      day: ['dia', 'dias'],
    },
    hourly: ['(a )?cada hora', 'de hora em hora', 'toda hora'],
    halfHour: ['(a )?cada meia hora', 'de meia em meia hora'],
  },
  daily: {
    day: ['todo dia', 'todos os dias', 'diariamente', '(a )?cada dia'],
    morning: ['toda manhã', 'toda manha', 'todas as manhãs', 'todas as manhas', '(a )?cada manhã'],
    afternoon: ['toda tarde', 'todas as tardes', '(a )?cada tarde'],
    evening: [],
    night: ['toda noite', 'todas as noites', '(a )?cada noite'],
  },
  dayparts: {
    morning: ['manhã', 'manha', 'manhãs', 'madrugada'],
    afternoon: ['tarde', 'tardes'],
    evening: [],
    night: ['noite', 'noites'],
  },
  weekly: {
    before: ['toda', 'todo', 'todas as', 'todos os', '(a )?cada', 'às', 'aos', 'nas', 'nos', 'na', 'no'],
    after: [],
    days: [
      ['domingo', 'domingos'],
      ['segunda-feira', 'segundas-feiras', 'segunda feira', 'segunda', 'segundas'],
      ['terça-feira', 'terças-feiras', 'terça feira', 'terça', 'terças', 'terca'],
      ['quarta-feira', 'quartas-feiras', 'quarta feira', 'quarta', 'quartas'],
      ['quinta-feira', 'quintas-feiras', 'quinta feira', 'quinta', 'quintas'],
      ['sexta-feira', 'sextas-feiras', 'sexta feira', 'sexta', 'sextas'],
      ['sábado', 'sábados', 'sabado', 'sabados'],
    ],
  },
  once: {
    once: ['uma vez', 'uma única vez', 'uma so vez', 'uma só vez'],
    today: ['hoje'],
    tomorrow: ['amanhã', 'amanha', 'depois de amanhã'],
  },
  clock: {
    at: ['às', 'as', 'por volta das'],
    hour: ['h', 'hs', 'horas'],
    minute: [],
    half: ['e meia'],
    am: [],
    pm: [],
    meridiemFirst: false,
  },
  notify: {
    none: [
      'não me (notifique|avise)',
      'não (notifique|notificar|avise)',
      'sem (notificação|notificações|aviso|avisos)',
      '(só|apenas) (salvar|salve|guardar|guarde)',
    ],
    change: [
      '(quando|se) (mudar|houver mudanças|tiver mudanças|algo mudar)',
      '(quando|se) (a página|o resultado|o conteúdo) mudar',
      '(só|apenas) quando mudar',
    ],
    significant: ['(só se|só quando|apenas se|se|quando)…(importante|significativo|relevante)', 'valer (uma notificação|um aviso)'],
    available: [
      '(voltar|volte) ao estoque',
      'de volta ao estoque',
      '(voltar|volte) a ficar disponível',
      'em estoque',
      '(estiver|ficar|estará|está|esteja) disponível',
      'esgotado',
    ],
    below: ['abaixo de', 'menos de', 'menor (que|do que)', 'inferior a', 'baixar de', 'cair abaixo de', 'mais barato que'],
    above: ['acima de', 'mais de', 'maior (que|do que)', 'superior a', 'passar de', 'ultrapassar', 'mais caro que'],
    belowAfter: [],
    aboveAfter: [],
  },
  currencies: { real: 'BRL', reais: 'BRL', 'r$': 'BRL', dólar: 'USD', dólares: 'USD' },
  multipliers: { mil: 1000 },
  currency: 'BRL',
  names: {
    stock: ['estoque', 'esgotado'],
    release: ['versão', 'versões', 'lançamento', 'lançamentos'],
    research: ['pesquisa', 'pesquise', 'pesquisar'],
  },
  task: {
    dropAtEnd: [
      ' e (me avise|avise-me|me diga|me notifique|me informe) se o preço (ficar|estiver|for|cair|baixar|subir) (abaixo|acima) de #',
    ],
    price: ['preço', 'preços', 'preco'],
    reportPrice: 'Informe o preço atual',
    fullStop: '. ',
  },
}
